language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer selfupdate
  - sudo apt-get update -qq
  - sudo apt-get install mupdf

install: composer update --prefer-dist --no-interaction

script: phpunit

